# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "TFC\ Alloys.o"
LINKOBJ  = "TFC Alloys.o"
LIBS     = -L"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/lib" -L"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -lmingw32 -lSDLmain -lSDL -lSDL_ttf
INCS     = -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/include" -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/include" -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/OneDrive/Not School/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Exe/TFC Alloys.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"TFC\ Alloys.o": TFC\ Alloys.cpp
	$(CPP) -c "TFC Alloys.cpp" -o "TFC Alloys.o" $(CXXFLAGS)
